FROM silkeh/clang

RUN apt-get update -y
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y git ninja-build cmake

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Copied from https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container

RUN ln -sT /usr/local/bin/clang /usr/bin/cc
RUN ln -sT /usr/local/bin/clang++ /usr/bin/c++

RUN apt-get install -y sudo
RUN apt-get install -y python3 clang
# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME --shell /bin/bash \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
